/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 laptop.glb 
Author: ℜ𝔢𝔞𝔩 𝔖𝔩𝔦𝔪 𝔖𝔥𝔞𝔡𝔶 (https://sketchfab.com/real_slimshady)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/laptop-3d-model-ba56c75ff9f4430da10cd3d283da7358
Title: Laptop 3D Model
*/

import { useGLTF } from '@react-three/drei'

export function Laptop(props) {
  const { nodes, materials } = useGLTF('/models/laptop.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-0.005, 0.044, 0.15]} rotation={[0, 0, -Math.PI]} scale={[0.288, 0.412, 0.295]}>
          <mesh geometry={nodes['Material19-material-material'].geometry} material={materials['Material19-material']} />
          <mesh geometry={nodes['Material20-material-material'].geometry} material={materials['Material20-material']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/laptop.glb')
